TFSOLO.BalancingFuncs.push(function(kv)
{
	// Steel-Toed Stompers
	local key1 = kv.FindKey("items")
	local prefab = key1.FindKey("563")
	local attrib = prefab.GetKey("attributes", true)
	// Set as Heavy secondary
	prefab.SetString("prefab","valve base_misc")
	prefab.SetString("item_slot","secondary")
	prefab.SetString("item_class","tf_weapon_parachute_secondary")
	prefab.SetString("anim_slot","FORCE_NOT_USED")
	prefab.SetString("loadondemand","1")
	prefab.SetString("show_in_armory","1")
	prefab.SetString("item_type_name","#TF_Wearable_Costume")
	prefab.SetString("drop_type","none")
	prefab.SetString("item_quality","unique")
	prefab.SetString("min_ilevel","10")
	prefab.SetString("max_ilevel","10")
	prefab.SetString("image_inventory_size_w","128")
	prefab.SetString("image_inventory_size_h","82")
	prefab.SetString("mouse_pressed_sound","ui/item_hat_pickup.wav")
	prefab.SetString("drop_sound","ui/item_hat_drop.wav")
	local capable = prefab.GetKey("capabilities", true)
	capable.SetString("nameable","1")
	prefab.SetString("model_player","models/player/items/heavy/hwn_heavy_misc2.mdl")
	prefab.SetString("extra_wearable","models/player/items/heavy/hwn_heavy_misc2.mdl")
	// Add knockback immunity
	local a1 = attrib.GetKey("knockback_immunity", true)
	a1.SetString("attribute_class","knockback_immunity")
	a1.SetInt("value", 1)
	// Add cannot swim
	local a2 = attrib.GetKey("cannot_swim", true)
	a2.SetString("attribute_class","cannot_swim")
	a2.SetInt("value", 1)
})